# Generated by Django 5.1 on 2024-08-25 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message_read'),
        ('user_profile', '0002_remove_request_password_request_encrypted_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visible', models.BooleanField(default=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visibility', to='chat.chat')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visibility', to='user_profile.profile')),
            ],
        ),
    ]
