# Generated by Django 5.0.6 on 2024-07-01 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_rename_address_teacher_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(default='default_profile.jpg', upload_to='profile_imgs'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='stars',
            field=models.FloatField(default=0),
        ),
    ]
