# Generated by Django 5.1 on 2024-08-26 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_remove_request_password_request_encrypted_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='city',
            field=models.CharField(default=' ', max_length=30),
        ),
    ]
