# Generated by Django 5.0.6 on 2024-07-02 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_alter_profile_picture_alter_teacher_stars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='tel_number',
        ),
        migrations.AddField(
            model_name='profile',
            name='tel_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
