# Generated by Django 5.0.6 on 2024-07-02 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_remove_teacher_tel_number_profile_tel_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
