# Generated by Django 5.1 on 2024-08-26 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_alter_teacher_city_alter_teacher_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='subjects',
            field=models.CharField(default='Insert subjects comma separated', max_length=255),
        ),
    ]
