# Generated by Django 5.0.6 on 2024-07-02 10:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_alter_teacher_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='price',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0, message='Value must be greater than or equal to 0')]),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='stars',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0, message='Value must be greater than or equal to 0.0'), django.core.validators.MaxValueValidator(5.0, message='Value must be less than or equal to 5.0')]),
        ),
    ]
