# Generated by Django 5.0.6 on 2024-07-03 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0006_alter_teacher_price_alter_teacher_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='city',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='subjects',
            field=models.CharField(max_length=100),
        ),
    ]
