# Generated by Django 5.0.6 on 2024-07-29 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0009_alter_teacher_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tel_number',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
