# Generated by Django 5.0.6 on 2024-08-02 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0010_alter_profile_tel_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='teacher',
            new_name='profile',
        ),
    ]
