# Generated by Django 5.0.6 on 2024-07-02 15:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_alter_lesson_student_alter_lesson_teacher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='stars',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='Value must be greater than or equal to 0'), django.core.validators.MaxValueValidator(5, message='Value must be less than or equal to 5')]),
        ),
    ]
