# Generated by Django 5.0.6 on 2024-07-03 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_availability_available_alter_rating_stars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availability',
            name='available',
        ),
    ]
