# Generated by Django 5.0.6 on 2024-07-05 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_remove_availability_available'),
        ('user_profile', '0009_alter_teacher_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availability',
            name='teacher',
        ),
        migrations.AddField(
            model_name='availability',
            name='teacher',
            field=models.ManyToManyField(to='user_profile.profile'),
        ),
    ]
