# Generated by Django 5.0.6 on 2024-07-31 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0005_remove_availability_teacher_availability_teacher'),
        ('user_profile', '0010_alter_profile_tel_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availability',
            name='teacher',
        ),
        migrations.AlterField(
            model_name='rating',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_rating', to='user_profile.profile'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_rating', to='user_profile.profile'),
        ),
        migrations.AddField(
            model_name='availability',
            name='teacher',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_availability', to='user_profile.profile'),
            preserve_default=False,
        ),
    ]
