# Generated by Django 5.0.6 on 2024-08-02 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0006_remove_availability_teacher_alter_rating_student_and_more'),
        ('user_profile', '0011_rename_teacher_teacher_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_availability', to='user_profile.teacher'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_lessons', to='user_profile.teacher'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_rating', to='user_profile.teacher'),
        ),
    ]
