# Generated by Django 5.0.6 on 2024-08-06 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0007_alter_availability_teacher_alter_lesson_teacher_and_more'),
        ('user_profile', '0011_rename_teacher_teacher_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='user_profile.teacher'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='subject',
            field=models.CharField(max_length=15),
        ),
    ]
